# Generated by Django 3.2 on 2024-12-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHora',
            fields=[
                ('bh_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bh_dia', models.DateField(verbose_name='Fecha')),
                ('bh_hora_inicio', models.TimeField()),
                ('bh_hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('promocion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promocion_precio', models.IntegerField(verbose_name='Descuento en CLP: ')),
                ('promocion_descripcion', models.CharField(max_length=200, verbose_name='Descripción: ')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_nombreUsuario', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Ingrese un nombre de usuario único: ')),
                ('usuario_password', models.CharField(max_length=20, verbose_name='Ingrese una contraseña: ')),
                ('usuario_tipo', models.CharField(max_length=15, verbose_name='Tipo de usuario: administrador, trabajador, cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='spa.usuario')),
                ('cliente_nombreCliente', models.CharField(max_length=50, verbose_name='Nombre y Apellido: ')),
                ('cliente_direccion', models.CharField(max_length=200, verbose_name='Dirección: ')),
                ('cliente_telefono', models.IntegerField(verbose_name='Número de teléfono: ')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_precio', models.IntegerField(verbose_name='Precio del servicio: ')),
                ('servicio_descripcion', models.CharField(max_length=200, verbose_name='Descripción: ')),
                ('servicio_imagenes', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen Portada')),
                ('servicio_bh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='spa.bloquehora')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_promocion_aplicadas', to='spa.promocion', verbose_name='Promoción asociada')),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_reserva_promocion', to='spa.reserva', verbose_name='Reserva asociada')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_reserva_promocion', to='spa.servicio', verbose_name='Servicio asociado')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_servicios',
            field=models.ManyToManyField(related_name='reservas', through='spa.ReservaPromocion', to='spa.Servicio'),
        ),
        migrations.CreateModel(
            name='PromocionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_promocion_servicio', to='spa.promocion', verbose_name='Promociones aplicables')),
                ('servicios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_promocion_servicio', to='spa.servicio', verbose_name='Servicios aplicables')),
            ],
        ),
        migrations.AddField(
            model_name='promocion',
            name='promocion_servicios',
            field=models.ManyToManyField(related_name='promociones', through='spa.PromocionServicio', to='spa.Servicio', verbose_name='Servicios aplicables'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='spa.cliente'),
        ),
    ]
