# Generated by Django 3.2 on 2024-11-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHora',
            fields=[
                ('bh_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bh_hora_inicio', models.TimeField()),
                ('bh_hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('dia_id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('promocion_id', models.AutoField(primary_key=True, serialize=False)),
                ('promocion_precio', models.IntegerField(verbose_name='Precio del servicio: ')),
                ('promocion_descripcion', models.CharField(max_length=200, verbose_name='Descripción: ')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserva_precioTotal', models.IntegerField()),
                ('reserva_promos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaPromos', to='spa.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_precio', models.IntegerField(verbose_name='Precio del servicio: ')),
                ('servicio_descripcion', models.CharField(max_length=200, verbose_name='Descripción: ')),
                ('servicio_imagenes', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen Portada')),
                ('servicio_bh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='spa.bloquehora')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_nombreUsuario', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Ingrese un nombre de usuario único: ')),
                ('usuario_password', models.CharField(max_length=20, verbose_name='Ingrese una contraseña: ')),
                ('usuario_tipo', models.CharField(max_length=15, verbose_name='Tipo de usuario: administrador, trabajador, cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spa.usuario')),
                ('cliente_nombreCliente', models.CharField(max_length=50, verbose_name='Nombre y Apellido: ')),
                ('cliente_direccion', models.CharField(max_length=200, verbose_name='Dirección: ')),
                ('cliente_telefono', models.IntegerField(verbose_name='Número de teléfono: ')),
            ],
            bases=('spa.usuario',),
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_servicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaServicios', to='spa.servicio'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='promocion_servicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='spa.servicio'),
        ),
        migrations.AddField(
            model_name='bloquehora',
            name='bh_dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='spa.dia'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='reserva_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='spa.cliente'),
        ),
    ]
