# Generated by Django 3.2 on 2024-12-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_password',
            field=models.CharField(max_length=255, verbose_name='Ingrese una contraseña: '),
        ),
    ]
