# Generated by Django 3.2 on 2024-12-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nombreUsuario',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Ingrese un nombre de usuario único: '),
        ),
    ]
