# Generated by Django 3.2 on 2024-12-25 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spa', '0002_alter_usuario_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_telefono',
            field=models.TextField(max_length=20, verbose_name='Número de teléfono: '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
