# Generated by Django 3.2 on 2024-12-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_promocion_servicio', to='spa.promocion', verbose_name='Promociones aplicables')),
                ('servicios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_promocion_servicio', to='spa.servicio', verbose_name='Servicios aplicables')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_promocion_aplicadas', to='spa.promocion', verbose_name='Promoción asociada')),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_reserva_promocion', to='spa.reserva', verbose_name='Reserva asociada')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_reserva_promocion', to='spa.servicio', verbose_name='Servicio asociado')),
            ],
        ),
        migrations.DeleteModel(
            name='ReservaServicioPromocion',
        ),
        migrations.AlterField(
            model_name='promocion',
            name='promocion_servicios',
            field=models.ManyToManyField(related_name='promociones', through='spa.PromocionServicio', to='spa.Servicio', verbose_name='Servicios aplicables'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='reserva_servicios',
            field=models.ManyToManyField(related_name='reservas', through='spa.ReservaPromocion', to='spa.Servicio'),
        ),
    ]
